name: Maven build exporter then pack docker image and Push

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '8'
        
    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: ./src/main/docker/Dockerfile
        tags: 942878658013.dkr.ecr.eu-central-1.amazonaws.com/devops/rocketmq-exporter:${{ github.ref_name }}

    - name: Push Docker Image to AWS ECR
      run: |
        docker push 942878658013.dkr.ecr.eu-central-1.amazonaws.com/devops/rocketmq-exporter:${{ github.ref_name }}
        docker tag 942878658013.dkr.ecr.eu-central-1.amazonaws.com/devops/rocketmq-exporter:${{ github.ref_name }} 942878658013.dkr.ecr.eu-central-1.amazonaws.com/devops/rocketmq-exporter:latest
        docker push 942878658013.dkr.ecr.eu-central-1.amazonaws.com/devops/rocketmq-exporter:latest